# Generated by Django 4.2.8 on 2024-01-30 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mySite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
